[project]
name = "delunet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "parv", email = "parv@rhour.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
    "torch>=2.14.0",
]

[project.scripts]
delunet = "delunet:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
